# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Keyforge < Formula
  desc "SOPS multi-key lifecycle management CLI"
  homepage "https://github.com/danpet-dev/keyforge"
  version "0.3.0"
  license "MIT"

  depends_on "age"
  depends_on "gnupg"
  depends_on "sops"

  on_macos do
    on_intel do
      url "https://github.com/danpet-dev/keyforge/releases/download/v0.3.0/keyforge_0.3.0_darwin_amd64.tar.gz"
      sha256 "e85431dbd2af86bb0aae967858cbcf3993dd43449a1ca48d4bf161849a80b92e"

      def install
        bin.install "keyforge"
      end
    end
    on_arm do
      url "https://github.com/danpet-dev/keyforge/releases/download/v0.3.0/keyforge_0.3.0_darwin_arm64.tar.gz"
      sha256 "a105ac426827af3d1d79e4dbdd3d06085b9d20f912baaf0f96e48347d99083e2"

      def install
        bin.install "keyforge"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/danpet-dev/keyforge/releases/download/v0.3.0/keyforge_0.3.0_linux_amd64.tar.gz"
        sha256 "7b2c82dc30f30df461dc9d2e6663ec4009379515abbf3d5ef49677a8ea8d58fb"

        def install
          bin.install "keyforge"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/danpet-dev/keyforge/releases/download/v0.3.0/keyforge_0.3.0_linux_arm64.tar.gz"
        sha256 "033bae443833ed2b7c11facc733f705f132f775b785f8b8bf0de569ccc51ab57"

        def install
          bin.install "keyforge"
        end
      end
    end
  end
end
