# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Keyforge < Formula
  desc "SOPS multi-key lifecycle management CLI"
  homepage "https://github.com/danpet-dev/keyforge"
  version "0.3.1"
  license "MIT"

  depends_on "age"
  depends_on "gnupg"
  depends_on "sops"

  on_macos do
    on_intel do
      url "https://github.com/danpet-dev/keyforge/releases/download/v0.3.1/keyforge_0.3.1_darwin_amd64.tar.gz"
      sha256 "697481df5e884f5abc32228622e3ed674a537b592b3a3d4570d9d120462e97f9"

      def install
        bin.install "keyforge"
      end
    end
    on_arm do
      url "https://github.com/danpet-dev/keyforge/releases/download/v0.3.1/keyforge_0.3.1_darwin_arm64.tar.gz"
      sha256 "7276ebca903f13dae3a399336a3e45bc8feeecdb50d47a6e7b8bd8456f5df497"

      def install
        bin.install "keyforge"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/danpet-dev/keyforge/releases/download/v0.3.1/keyforge_0.3.1_linux_amd64.tar.gz"
        sha256 "ebb2075579684b46ce34b0ebc2945a6fece9e988aab6f07796657c198c977414"

        def install
          bin.install "keyforge"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/danpet-dev/keyforge/releases/download/v0.3.1/keyforge_0.3.1_linux_arm64.tar.gz"
        sha256 "b8e7644549075a2d3c263d504fc6140e8f1075b909d973433f443d228dfb11cd"

        def install
          bin.install "keyforge"
        end
      end
    end
  end
end
